### ISSUE TITLE
Progress Tracking

### ISSUE THREAD

**Issue by andrewvy** [andrewvy/handmade_quake#1]
Author's Blog: http://philipbuuck.com/handmadequake
Video Playlist: [HandmadeQuake](https://www.youtube.com/playlist?list=PLBKDuv-qJpTbCsXHsxcoSSsMarnfyNhHF)
- [x] 1.1 - The Beginning
- [x] 1.2 - Parsing the Command Line
- [x] 1.3 - Replacing strcmp and atoi
- [x] 1.4 - Adding Source Code, Headers, and more STL
- [x] 1.5 - const, and the Module 1 Wrapup
- [x] 2.1 - Creating a Window
- [x] 2.2 - Building the Game Loop
- [x] 2.3 - Timing the Game Loop
- [x] 2.4 - More Timing
- [x] 2.5 - Timesteps and Platform Independence
- [x] 2.6 - Quake Timesteps vs. Ours
- [x] 3.1 - Intro to Quake Graphics
- [x] 3.2 - Creating and Drawing into a Win32 Window
- [x] 3.3 - 8bit vs 32bit Graphics in Windows
- [x] 3.4 - Drawing Quake Assets From Disc
- [x] 3.5 - Integrating Video in Quake
- [x] 3.6 - All the Screen Resolutions!
- [x] 4.1 - File Management and Varargs!
- [ ] 4.2 - Wrapping the File Functions
- [ ] 4.3 - Loading Quake's Pak Files
- [ ] 4.4 - Game Directories and File Loading
- [ ] 4.5 - Plugging the File System in HQ
- [ ] 4.6 - Loading Quake Assets at Will
